services:
  web:
    build: .
    command: python src/manage.py runserver 0.0.0.0:8000
    working_dir: /test_api_gallery
    volumes:
      - .:/test_api_gallery
    ports:
      - 8000:8000
    env_file:
      - .env
    depends_on:
      - db
    restart: always
  db:
    image: postgres:14
    env_file:
      - .env
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    ports:
      - 5432:5432
volumes:
  postgres_data: