services:
  web:
    build: .
    command:  bash -c "
        python src/manage.py makemigrations users
        && python src/manage.py makemigrations gallery
        && python src/manage.py migrate
        && python src/manage.py create_admin
        && python src/manage.py runserver 0.0.0.0:8000
      "
    working_dir: /test_api_gallery
    volumes:
      - .:/test_api_gallery
    ports:
      - 8000:8000
    env_file:
      - .env
    depends_on:
      - db
    restart: always
  db:
    image: postgres:14
    env_file:
      - .env
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    ports:
      - 5432:5432
  lint:
    build: .
    command: bash -c "mypy src ; pylint src ; flake8"
    working_dir: /test_api_gallery
    profiles: ["test_profile"]
    volumes:
      - .:/test_api_gallery
  test:
    build: .
    command: python -m  pytest src
    working_dir: /test_api_gallery
    profiles: ["test_profile"]
    volumes:
      - .:/test_api_gallery src
    depends_on:
      - db
volumes:
  postgres_data: